### ISSUE TITLE
Discovery problem in Home Assistant for thermostat G0

### ISSUE THREAD

**Issue by MortenVinding** [misery/HeatingMqttBridge#22]
Hi André,

Thank you for the mail :)

I have just installed your add-on on my Home Assistant, awesome job 👍

I have discovered one problem though:
I have 12 thermostats but one of them is simply not showing, on investigation I have found out that it does provide the sensor component but not the climate component.

It's the first of my thermostats and the problem seems to be that the temp_unit is empty in the discovery topic.

{"name":"Teknik","mode_cmd_t":"roth/G0/set/OPMode","mode_stat_t":"roth/G0/OPMode_mode","avty":[{"topic":"roth/G0/available"},{"topic":"roth/available"}],"avty_mode":"all","temp_cmd_t":"roth/G0/set/SollTemp","temp_stat_t":"roth/G0/SollTemp","curr_temp_t":"roth/G0/RaumTemp","temp_unit":"","min_temp":"5.00","max_temp":"30.00","temp_step":"0.5","modes":["off","heat"],"device":{"identifiers":"ROTH-015FD9","name":"ROTH-015FD9","cns":[["mac","5C:C2:13:01:5F:D9"]]},"unique_id":"ROTH-015FD9-G0"}

As soon as I publish the JSON with temp_unit set to something ("C"), the entity pops up in my Home Assistant.

It looks like the "TempSIUnit" topic is also missing in the device topic (roth), but it doesn't matter so much.

One small thing more:
the normal Roth Touchline integration does not provide option for changing mode of the thermostat, that means the climate card is smaller, and I personally newer change mode of the thermostat anyway.

With mode:
<img width="92" alt="Screenshot 2023-10-19 at 00 41 36" src="https://github.com/misery/HeatingMqttBridge/assets/1188091/de5d2917-18e6-4208-86fa-7fb5968da312">

Without mode:
<img width="96" alt="Screenshot 2023-10-19 at 00 45 00" src="https://github.com/misery/HeatingMqttBridge/assets/1188091/ca047422-e318-426b-9910-a05da16f22da">

Maybe it could be selectable in the config... just a thought :)

Thank you for the great work

/Morten

**Comment by misery** [comment]
Thanks for testing! I pushed v1.6 so you can use ```G0/set/TempSIUnit``` to set it. Hopefully it will fix that faulty state on the energylogic as it is really strange. Otherwise I need to use a default value if it is still empty.

Yeah, I understand that the default thermostat is really big in home assistant. I use the simple ones of https://github.com/nervetattoo/simple-thermostat. Maybe this is something for you? I will think about it to add an option to disable the feature. :-)

**Comment by misery** [comment]
@MortenVinding did you test it?

**Comment by MortenVinding** [comment]
> @MortenVinding did you test it?

Hi André,

Sorry, yes I did install 1.6 but it made no difference.

But now I get this in the log when it starts:
2023-11-01 20:39:36 DBG Use internal DNS cache
2023-11-01 20:39:36 INF Host: ROTH-015FD9
2023-11-01 20:39:36 INF Add room: G0
2023-11-01 20:39:36 INF Add room: G1
2023-11-01 20:39:36 INF Add room: G2
2023-11-01 20:39:36 INF Add room: G3
2023-11-01 20:39:36 INF Add room: G4
2023-11-01 20:39:36 INF Add room: G5
2023-11-01 20:39:36 INF Add room: G6
2023-11-01 20:39:36 INF Add room: G7
2023-11-01 20:39:36 INF Add room: G8
2023-11-01 20:39:36 INF Add room: G9
2023-11-01 20:39:36 INF Add room: G10
2023-11-01 20:39:36 INF Add room: G11
2023-11-01 20:39:36 WRN TempSIUnit of G0 is undefined. Use roth/set/G0/TempSIUnit

**Comment by misery** [comment]
@MortenVinding Just to be sure... you tried to set it via publishing ```C``` as value to ```roth/set/G0/TempSIUnit```?

**Comment by MortenVinding** [comment]
> @MortenVinding Just to be sure... you tried to set it via publishing `C` as value to `roth/set/G0/TempSIUnit`?

Yes I did :)

But shouldn't it pull it from the controller?
I havn't changed anything for the other thermostats.

**Comment by misery** [comment]
Sorry, for that big delay.
Yeah, it pulls it from the controller. But it looks like the controller gives a bad value. My "setter" set the TempSIUnit to the controller.

Could you try this? It will show the output from the controller.

```
curl -d "<content><field><n>G0.name</n></field><field><n>G0.kurzID</n></field><field><n>G0.ownerKurzID</n></field><field><n>G0.OPMode</n></field><field><n>G0.OPModeEna</n></field><field><n>G0.TempSIUnit</n></field><field><n>G0.WeekProg</n></field><field><n>G0.WeekProgEna</n></field><field><n>G0.RaumTemp</n></field><field><n>G0.SollTemp</n></field><field><n>G0.SollTempStepVal</n></field><field><n>G0.SollTempMinVal</n></field><field><n>G0.SollTempMaxVal</n></field></content>" -H "Content-Type: text/xml" -X POST http://IP_OF_ROTH/cgi-bin/ILRReadValues.cgi
```
